"use strict";
exports.__esModule = true;
var moment = require("moment");
require("moment/locale/pt-br");
var randomExt = require("random-ext");
var firstTs = moment("02-26-2023 19:43").format();
console.log(firstTs);
var randomize = randomExt.integer(15, 10);
console.log(randomize);
var secondRandomize = randomExt.float(10.53, 2.85).toFixed(2);
console.log(secondRandomize);
